// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crgrsnrszldsknrxfrpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZ3JzbnJzemxkc2tucnhmcnB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMjk5MTksImV4cCI6MjA2ODgwNTkxOX0.BKzKwL7clcWsuLdSZfM5HIx3I-rzX1VFd3mxDrS3rt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});